### ISSUE TITLE
docker-py 1.10.0 Seems to be broken

### ISSUE THREAD

**Issue by rcoh** [angstwad/docker.ubuntu#109]
This isn't a problem with docker.ubuntu, but maybe it should be pinned to 1.9.0 until it is resolved:
After installing docker.ubuntu, when you try to actually do any docker commands, in this case, `docker_login` 
```
{"changed": false, "failed": true, "msg": "Failed to import docker-py - No module named types. Try `pip install docker-py`"}
```

**Comment by rcoh** [comment]
The fix:
```- { role: angstwad.docker_ubuntu, pip_version_docker_py: 1.9.0 }```

**Comment by rcoh** [comment]
Fixed upstream.

**Comment by krzkaczor** [comment]
I believe that it's still not fixed. I have just run into this issue.
